const products = [
  {
    _id: 'p1',
    name: 'Hiskywin Full Zip Running Shirts Thermal Workout',
    image: '/images/product-1.jpg',
    description: 'It is cool',
    price: 100,
    brand: 'Nike',
    rating: 3.5,
    numReviews: 123,
    countInStock: 5,
    reviews: [
      {
        _id: 'r1',
        name: 'Bob',
        rating: 4,
        comment: 'nice one.',
        createdAt: '2020-06-06',
      },
      {
        _id: 'r2',
        name: 'Joe',
        rating: 5,
        comment: 'great product',
        createdAt: '2020-06-07',
      },
      {
        _id: 'r3',
        name: 'Sara',
        rating: 2,
        comment: 'not bad',
        createdAt: '2020-06-08',
      },
    ],
  },
  {
    _id: 'p2',
    name: 'Relax Shirt',
    image: '/images/product-2.jpg',
    description: 'It is cool',
    price: 25,
    brand: 'Nike',
    rating: 4.5,
    numReviews: 123,
    countInStock: 15,
    reviews: [],
  },
  {
    _id: 'p3',
    name: 'Fancy Fit Shirt',
    image: '/images/product-3.jpg',
    description: 'It is cool',
    price: 20,
    brand: 'Nike',
    rating: 2.3,
    numReviews: 123,
    countInStock: 10,
    reviews: [
      {
        _id: 'r3',
        name: 'Sara',
        rating: 2,
        comment: 'not bad',
        createdAt: '2020-06-08',
      },
    ],
  },
  {
    _id: 'p4',
    name: 'Cool Fit Shirt',
    image: '/images/product-4.jpg',
    description: 'It is cool',
    price: 40,
    brand: 'Nike',
    rating: 4.9,
    numReviews: 123,
    countInStock: 0,
    reviews: [],
  },
  {
    _id: 'p5',
    name: 'Best Fit Shirt',
    image: '/images/product-5.jpg',
    description: 'It is cool',
    price: 60,
    brand: 'Nike',
    rating: 4.3,
    numReviews: 123,
    countInStock: 0,
    reviews: [],
  },
  {
    _id: 'p6',
    name: 'Top Fit Shirt',
    image: '/images/product-6.jpg',
    description: 'It is cool',
    price: 12,
    brand: 'Nike',
    rating: 3.8,
    numReviews: 123,
    countInStock: 0,
    reviews: [],
  },
];

export default products;
